# Three-Dimensional Geometry in Python
## Introduction
Three-dimensional (3D) geometry involves points, vectors, planes, and transformations in 3D space. Common operations include:

* **Distance & midpoint calculations**
* **Dot & cross product of vectors**
* **Equation of a plane**
* **3D transformations (translations, rotations, scalings)**

## Distance Between Two Points

The distance between two points $ (x_1, y_1, z_1) $ and $ (x_2, y_2, z_2) $ is:

$$
d = \sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2 + (z_2 - z_1)^2}
$$

In [1]:
import numpy as np

def distance_3d(p1, p2):
    return np.linalg.norm(np.array(p2) - np.array(p1))

# Example: Distance between (1, 2, 3) and (4, 5, 6)
print(distance_3d((1, 2, 3), (4, 5, 6)))


5.196152422706632


## Midpoint of Two Points

The midpoint between two points $ (x_1, y_1, z_1) $ and $ (x_2, y_2, z_2) $ is:

$$
M = \left( \frac{x_1 + x_2}{2}, \frac{y_1 + y_2}{2}, \frac{z_1 + z_2}{2} \right)
$$

In [2]:
def midpoint_3d(p1, p2):
    return (np.array(p1) + np.array(p2)) / 2

# Example: Midpoint between (1, 2, 3) and (4, 5, 6)
print(midpoint_3d((1, 2, 3), (4, 5, 6)))


[2.5 3.5 4.5]


## Dot Product of Two Vectors

The dot product of two vectors **A** and **B** is calculated as:

$$
A \cdot B = x_1 x_2 + y_1 y_2 + z_1 z_2
$$

Where:
- $ x_1, y_1, z_1 $ are the components of vector **A**.
- $ x_2, y_2, z_2 $ are the components of vector **B**.

In [3]:
def dot_product_3d(v1, v2):
    return np.dot(v1, v2)

# Example: Dot product of (1, 2, 3) and (4, 5, 6)
print(dot_product_3d((1, 2, 3), (4, 5, 6)))

32


## Cross Product of Two Vectors

The cross product of two vectors **A** and **B** results in a perpendicular vector:

$$
A \times B =
\begin{vmatrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
x_1 & y_1 & z_1 \\
x_2 & y_2 & z_2
\end{vmatrix}
$$

In [4]:
def cross_product_3d(v1, v2):
    return np.cross(v1, v2)

# Example: Cross product of (1, 2, 3) and (4, 5, 6)
print(cross_product_3d((1, 2, 3), (4, 5, 6)))

[-3  6 -3]


## 5. Equation of a Plane

A plane can be defined by the equation:

$$ Ax + By + Cz + D = 0 $$

Where:
- \( A, B, C \) are the coefficients from the normal vector.
- \( x, y, z \) represent the coordinates of any point on the plane.
- \( D \) is the constant term.


In [5]:
def plane_equation(normal_vector, point):
    A, B, C = normal_vector
    D = -np.dot(normal_vector, point)
    return f"{A}x + {B}y + {C}z + {D} = 0"

# Example: Plane passing through (1, 2, 3) with normal vector (4, 5, 6)
print(plane_equation((4, 5, 6), (1, 2, 3)))


4x + 5y + 6z + -32 = 0


### 6. Transformations in 3D Space

#### Translation:
A point $ (x, y, z) $ moves by $ (dx, dy, dz) $, resulting in the new coordinates:

$$ x' = x + dx $$
$$ y' = y + dy $$
$$ z' = z + dz $$

Where:
- $ (x, y, z) $ represents the original coordinates of the point.
- $ (dx, dy, dz) $ is the translation vector indicating movement in the respective directions.
- $ (x', y', z') $ are the new coordinates after translation.

In [6]:
def translate_3d(point, dx, dy, dz):
    return np.array(point) + np.array([dx, dy, dz])

# Example: Move (1, 2, 3) by (5, -2, 4)
print(translate_3d((1, 2, 3), 5, -2, 4))


[6 0 7]


## Scaling:
A point $ (𝑥,𝑦,𝑧) $ scales by factor $ 𝑘 $ :

In [7]:
def scale_3d(point, k):
    return np.array(point) * k

# Example: Scale (1, 2, 3) by factor 2
print(scale_3d((1, 2, 3), 2))


[2 4 6]


## Rotation:
To rotate a point around an axis, we use **rotation matrices**. For simplicity, here’s **rotation about the Z-axis**:

In [9]:
def rotate_3d_z(point, theta):
    theta_rad = np.radians(theta)
    rotation_matrix = np.array([[np.cos(theta_rad), -np.sin(theta_rad), 0],
                                [np.sin(theta_rad), np.cos(theta_rad), 0],
                                [0, 0, 1]])
    return rotation_matrix @ np.array(point)

# Example: Rotate (1, 2, 3) by 45 degrees around the Z-axis
print(rotate_3d_z((1, 2, 3), 45))


[-0.70710678  2.12132034  3.        ]


## Summary
Using Python and NumPy, we explored:

* **Distance & midpoint calculations**
* **Dot & cross product**
* **Equation of a plane**
* **3D transformations (translation, scaling, rotation)**

These operations are essential for working with 3D graphics, simulations, and computational geometry.

# [Geometry Context](./README.md)